#!/usr/bin/env bash

set -euo pipefail

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
ARIS="$ROOT/skills/aris"
SENTINEL=".generated-by-sync-skill-links"

if [[ ! -f "$ARIS/skills/skills-codex/idea-discovery/SKILL.md" ]]; then
  echo "error: ARIS submodule is not initialized: $ARIS" >&2
  echo "run: git submodule update --init --recursive" >&2
  exit 1
fi

prepare_directory() {
  local relative_dir="$1"
  local directory="$ROOT/$relative_dir"
  local current_target=""
  local entry=""

  if [[ -L "$directory" ]]; then
    current_target="$(readlink "$directory")"
    if [[ "$current_target" != "../skills" ]]; then
      echo "error: refusing to replace $relative_dir -> $current_target" >&2
      exit 1
    fi
    rm "$directory"
  fi

  if [[ -d "$directory" && ! -f "$directory/$SENTINEL" ]]; then
    for entry in "$directory"/*; do
      if [[ -e "$entry" || -L "$entry" ]]; then
        echo "error: $relative_dir is not managed by this script" >&2
        exit 1
      fi
    done
  fi

  mkdir -p "$directory"
  printf '%s\n' "Generated by scripts/sync-skill-links.sh; do not edit links manually." \
    > "$directory/$SENTINEL"

  for entry in "$directory"/*; do
    [[ -L "$entry" ]] || continue
    rm "$entry"
  done
}

link_skill() {
  local relative_dir="$1"
  local name="$2"
  local source="$3"
  local destination="$ROOT/$relative_dir/$name"

  if [[ -e "$destination" || -L "$destination" ]]; then
    echo "error: duplicate or unmanaged skill name '$name' in $relative_dir" >&2
    exit 1
  fi

  ln -s "$source" "$destination"
}

link_local_skills() {
  local relative_dir="$1"
  local skill_dir=""
  local name=""

  for skill_dir in "$ROOT"/skills/*; do
    [[ -f "$skill_dir/SKILL.md" ]] || continue
    name="$(basename "$skill_dir")"
    link_skill "$relative_dir" "$name" "../../skills/$name"
  done
}

link_aris_main_skills() {
  local relative_dir="$1"
  local skill_dir=""
  local name=""

  for skill_dir in "$ARIS"/skills/*; do
    [[ -f "$skill_dir/SKILL.md" ]] || continue
    name="$(basename "$skill_dir")"
    link_skill "$relative_dir" "$name" "../../skills/aris/skills/$name"
  done

  link_skill "$relative_dir" "shared-references" \
    "../../skills/aris/skills/shared-references"
}

link_aris_codex_skills() {
  local relative_dir="$1"
  local skill_dir=""
  local name=""

  for skill_dir in "$ARIS"/skills/skills-codex/*; do
    [[ -f "$skill_dir/SKILL.md" ]] || continue
    name="$(basename "$skill_dir")"
    link_skill "$relative_dir" "$name" \
      "../../skills/aris/skills/skills-codex/$name"
  done

  link_skill "$relative_dir" "shared-references" \
    "../../skills/aris/skills/skills-codex/shared-references"
}

write_runtime_metadata() {
  mkdir -p "$ROOT/.aris"
  if [[ -e "$ROOT/.aris/tools" && ! -L "$ROOT/.aris/tools" ]]; then
    echo "error: refusing to replace non-symlink .aris/tools" >&2
    exit 1
  fi
  rm -f "$ROOT/.aris/tools"
  ln -s ../skills/aris/tools "$ROOT/.aris/tools"

  printf 'version\t1\nrepo_root\tskills/aris\nproject_root\t.\npackages\tmain\n' \
    > "$ROOT/.aris/installed-skills.txt"
  printf 'version\t1\nrepo_root\tskills/aris\nproject_root\t.\npackages\tskills-codex\n' \
    > "$ROOT/.aris/installed-skills-codex.txt"
}

for relative_dir in .agents/skills .claude/skills .cursor/skills; do
  prepare_directory "$relative_dir"
  link_local_skills "$relative_dir"
done

link_aris_codex_skills .agents/skills
link_aris_main_skills .claude/skills
link_aris_main_skills .cursor/skills
write_runtime_metadata

printf 'Codex skills: %s\n' "$(find "$ROOT/.agents/skills" -mindepth 1 -maxdepth 1 -type l | wc -l | tr -d ' ')"
printf 'Claude skills: %s\n' "$(find "$ROOT/.claude/skills" -mindepth 1 -maxdepth 1 -type l | wc -l | tr -d ' ')"
printf 'Cursor skills: %s\n' "$(find "$ROOT/.cursor/skills" -mindepth 1 -maxdepth 1 -type l | wc -l | tr -d ' ')"
